version: '3.8'

services:
  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker-in-Docker
      - backend_uploads:/app/uploads
      - backend_clones:/app/clones
    environment:
      - DEBUG=True
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - instantsite-network
    depends_on:
      - nginx

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - nginx_logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - instantsite-network

  # Redis (for future caching and session management)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - instantsite-network
    command: redis-server --appendonly yes

volumes:
  backend_uploads:
    driver: local
  backend_clones:
    driver: local
  nginx_logs:
    driver: local
  redis_data:
    driver: local

networks:
  instantsite-network:
    driver: bridge 